const STRINGS = {
  searchPlaceholder: "Search...",
  all: "All",
  noItemsFound: "No items found.",
  cartEmpty: "Your cart is empty",
  cartEmptyDescription: "Browse products to add them to your cart.",
  error: "Error",
  retry: "Retry",
  loadMore: "Load More...",
  orderFailed: "Order failed. Please try again.",
  unknownError: "Unknown error",
  placeOrder: "Place Order",
  total: "Total:",
  productFetchError: "Failed to load product",
  productNotFound: "Product not found",
  productDetailsTitle: "Product Details",
  notFoundTitle: "Oops!",
  notFoundMessage: "This screen doesn't exist.",
  notFoundLinkText: "Go to home screen!",
  category: "Category",
  inStock: "In Stock",
  addToCart: "Add to Cart",
  continueShopping: "Continue Shopping",
  recommendationsHeading: "Does anything catch your eye?",
  products: "Products",
  cart: "Cart",
  orderConfirmedTitle: "Order Confirmed!",
  orderConfirmedMessage: "Thank you for your purchase.",
};

export default STRINGS;
